from argparse import Namespace

def get_default_args(basepath):
    """Get default arguments for ScaleVLN model"""
    return Namespace(
        act_visited_nodes=False,
        angle_feat_size=4,
        aug=None,
        aug_data_paths=None, 
        aug_times=9,
        batch_size=4,
        bert_ckpt_file=None,
        connectivity_dir=f'{basepath}/dataset/connectivity/',
        dataset='r2r',
        debug=False,
        dropout=0.5,
        enc_full_graph=True,
        epochs=30,
        feat_dropout=0.4,
        feat_path=f'{basepath}/dataset/features/clip_vit-h14_mp3d_original.hdf5',
        features='clip.b16',
        fusion='dynamic',
        gamma=0.0,
        graph_sprels=True,
        id='debug',
        image_feat_size=1024,
        obj_feat_size=768,
        local_rank=-1,
        fix_lang_embedding=False,
        fix_local_branch=False,
        fix_pano_embedding=False,
        max_dialog_len=200,


        ignoreid=-100,
        resume_optimizer=False,
        detailed_output=False,

        iters=200000,
        log_every=500,
        log_every_epochs=1,
        lr=1e-5,
        max_action_len=15,
        max_instr_len=200,
        ml_weight=0.15,
        model_save_path='/DuetLoc/debug',
        num_l_layers=9,
        num_pano_layers=2,
        num_x_layers=4,
        optim='adamW',
        preload_all_features=False,
        preload_batch_features=True,
        resume_file=None,
        seed=0,
        tokenizer='bert',
        train=True,
        train_alg='dagger',
        train_data_path=f'{basepath}/modules/loc/DuetLoc/way_splits/train_data.json',
        valseen_data_path=f'{basepath}/modules/loc/DuetLoc/way_splits/valSeen_data.json',
        valunseen_data_path=f'{basepath}/modules/loc/DuetLoc/way_splits/valUnseen_data.json',
        wandb_log=False,
        world_size=1
    )