from argparse import Namespace

def get_default_args(basepath):
    """Get default arguments for ScaleVLN model"""
    return Namespace(
        nav_prob_mode='navigation_dialog_history',
        act_visited_nodes=True,
        disactivate_stop_node_jump=True,
        angle_feat_size=4,
        image_feat_size=1024,
        obj_feat_size=0,
        num_l_layers=9,
        num_pano_layers=2,
        num_x_layers=4,
        graph_sprels=True,
        feat_dropout=0.4,
        append_history=False,
        append_q=False,
        aug=None,
        aug_times=9,
        batch_size=4,
        mp3d_ft_files=f'{basepath}/dataset/features/clip_vit-h14_mp3d_original.hdf5',
        bert_ckpt_file=None,
        val_ft_file=f'{basepath}/dataset/features/clip_vit-h14_mp3d_original.hdf5',
        connectivity_dir=f'{basepath}/dataset/connectivity/',
        resume_file=f'{basepath}/dataset/checkpoints/best_val_unseen_wta',
        local_rank=-1,
        tokenizer='bert',
        fusion='dynamic', 
        fix_lang_embedding=False,
        fix_local_branch=False,
        fix_pano_embedding=False,
        dropout=0.5,
        world_size=1,
        optim='adamW',
        lr=1e-05,
        ignoreid=-100,
        resume_optimizer=False,
        seed=0,
        enc_full_graph=True,
        max_action_len=50,
        detailed_output=False,
        question_weight=1.0,
    ) 