from argparse import Namespace


def get_ag_default_args(basepath):
    return Namespace(
        # resume_file='/home/vln/00_backup/03_EXP_LANA/Q_gt_formatchange_val10_clip_0830T1108/ckpts/ckpt_24000',
        resume_file=f'{basepath}/checkpoints/lana_a',
        image_feat_size=512,
        use_clip16=True,
        img_ft_file=f'{basepath}/dataset/features/CLIP-ViT-B-16-views.tsv',
        connectivity_dir=f'{basepath}/dataset/connectivity/',
        scan_list=[],
        batch_size=8,
        angle_feat_size=4,
        seed=1,
        bpe_path=f'{basepath}/modules/qa/LANA/finetune_src/clip_tokenizer/bpe_simple_vocab_16e6.txt.gz',
        max_instr_len = 199,
        max_given_len = 1,
        max_action_len = 20,
        bert_ckpt_file=None,
        features='clip16',
        dataset='RAIN-i-qa',
        tokenizer='bert',
        local_rank=-1,
        eot_token=False,
        use_cache=False,

        ### not sure
        ignoreid=-100,

        scan_data_dir='../datasets/Matterport3D/v1_unzip_scans',
        anno_dir='../datasets/R2R/annotations',
        test_feedback='argmax',
        hist_envdrop=False,
        cand_use_ob_pos=False, 
        r4r_testall=False,
        multiple_saving=False,
        baseline_sr=45.0,
        debug=False,
        use_conn=True,
        rl_teacher_weight=0.4,
        rl_temperature=1.0,
        no_hist_mapping=False,
        rl_teacher_only=False,
        no_temporal=False,
        no_temporal_strategy='keep',
        no_path_restriction=False,
        logit_reweighting=False,
        root_dir='../datasets',
        output_dir='/home/vln/00_backup/03_EXP_LANA/Q_gt_formatchange_val10_clip_0905T1701',
        world_size=1,
        node_rank=0,
        iters=100000,
        log_every=2000,
        eval_first=True,
        ob_type='pano',
        test=False,
        resume_optimizer=False,
        aug=None,
        ml_weight=0.2,
        entropy_loss_weight=0.01,
        teacher_weight=1.0,
        fix_lang_embedding=False,
        fix_hist_embedding=False,
        fix_obs_embedding=False,
        num_l_layers=0,
        num_h_layers=0,
        num_x_layers=4,
        hist_enc_pano=True,
        hist_pano_num_layers=2,
        no_lang_ca=False,
        act_pred_token='ob',
        dropout=0.5,
        feat_dropout=0.4,
        submit=False,
        no_cand_backtrack=False,
        optim='adamW',
        lr=1e-05,
        weight_decay=0.0,
        feedback='sample',
        teacher='final',
        epsilon=0.1,
        views=36,
        vocab_size=30522,
        clip_lr=1e-05,
        task_name='caption',
        gamma=0.9,
        normalize_loss='total',
        vln_task_weight=5,
        caption_task_weight=1,
        caption_type='question',
        id='Q_gt_formatchange_val10_clip_0905T1701',
        wandb_log=True,
        train_seen_val=True,
        validation_size=0,
        train_size=0,
        ckpt_dir='/home/vln/00_backup/03_EXP_LANA/Q_gt_formatchange_val10_clip_0905T1701/ckpts'
    )


